//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class configuration {
    
    private string listenforField;
    
    private bool enabledField;
    
    private bool alertsField;
    
    private int confidenceField;
    
    public configuration() {
        this.listenforField = "";
        this.enabledField = true;
        this.alertsField = true;
        this.confidenceField = 60;
    }
    
    /// <remarks/>
    public string listenfor {
        get {
            return this.listenforField;
        }
        set {
            this.listenforField = value;
        }
    }
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public bool alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
    
    /// <remarks/>
    public int confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
}
