//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class configuration {
    
    private string aPIKeyField;
    
    private string latLngField;
    
    private int updateFrequencyField;
    
    private int fontSizeField;
    
    private string foregroundField;
    
    private string backgroundField;
    
    private bool displayBackgroundField;
    
    private int positionField;
    
    private string unitsField;
    
    private int gustLimitField;
    
    private int tempLimitField;
    
    private string statusEventField;
    
    private string displayTypeField;
    
    private string formatField;
    
    public configuration() {
        this.aPIKeyField = "";
        this.latLngField = "";
        this.updateFrequencyField = 10;
        this.fontSizeField = 12;
        this.foregroundField = "#ffffff";
        this.backgroundField = "#202020";
        this.displayBackgroundField = true;
        this.positionField = 1;
        this.unitsField = "standard";
        this.gustLimitField = 20;
        this.tempLimitField = 40;
        this.statusEventField = "";
        this.displayTypeField = "full";
        this.formatField = "{icon} {main}: {description}\r\nWind:{wind} Gust:{gust}\r\nTemp:{temp} Feels Like:{fe" +
            "elsLike}\r\nHumidity:{humidity} UVI:{uvi}";
    }
    
    /// <remarks/>
    public string APIKey {
        get {
            return this.aPIKeyField;
        }
        set {
            this.aPIKeyField = value;
        }
    }
    
    /// <remarks/>
    public string LatLng {
        get {
            return this.latLngField;
        }
        set {
            this.latLngField = value;
        }
    }
    
    /// <remarks/>
    public int UpdateFrequency {
        get {
            return this.updateFrequencyField;
        }
        set {
            this.updateFrequencyField = value;
        }
    }
    
    /// <remarks/>
    public int FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    public string Foreground {
        get {
            return this.foregroundField;
        }
        set {
            this.foregroundField = value;
        }
    }
    
    /// <remarks/>
    public string Background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <remarks/>
    public bool DisplayBackground {
        get {
            return this.displayBackgroundField;
        }
        set {
            this.displayBackgroundField = value;
        }
    }
    
    /// <remarks/>
    public int Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public int GustLimit {
        get {
            return this.gustLimitField;
        }
        set {
            this.gustLimitField = value;
        }
    }
    
    /// <remarks/>
    public int TempLimit {
        get {
            return this.tempLimitField;
        }
        set {
            this.tempLimitField = value;
        }
    }
    
    /// <remarks/>
    public string StatusEvent {
        get {
            return this.statusEventField;
        }
        set {
            this.statusEventField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayType {
        get {
            return this.displayTypeField;
        }
        set {
            this.displayTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}
