//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class configuration {
    
    private bool supportsAudioField;
    
    private bool supportsVideoField;
    
    private bool audioEnabledField;
    
    private bool videoEnabledField;
    
    private bool alertsEnabledField;
    
    private int volumeField;
    
    private int sizeField;
    
    public configuration() {
        this.supportsAudioField = true;
        this.supportsVideoField = true;
        this.audioEnabledField = true;
        this.videoEnabledField = true;
        this.alertsEnabledField = true;
        this.volumeField = 100;
        this.sizeField = 1;
    }
    
    /// <remarks/>
    public bool SupportsAudio {
        get {
            return this.supportsAudioField;
        }
        set {
            this.supportsAudioField = value;
        }
    }
    
    /// <remarks/>
    public bool SupportsVideo {
        get {
            return this.supportsVideoField;
        }
        set {
            this.supportsVideoField = value;
        }
    }
    
    /// <remarks/>
    public bool AudioEnabled {
        get {
            return this.audioEnabledField;
        }
        set {
            this.audioEnabledField = value;
        }
    }
    
    /// <remarks/>
    public bool VideoEnabled {
        get {
            return this.videoEnabledField;
        }
        set {
            this.videoEnabledField = value;
        }
    }
    
    /// <remarks/>
    public bool AlertsEnabled {
        get {
            return this.alertsEnabledField;
        }
        set {
            this.alertsEnabledField = value;
        }
    }
    
    /// <remarks/>
    public int Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public int Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
}
